spring.application.name=SplitIt!

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/splitit}
spring.datasource.username=${DB_USERNAME:splitit}
spring.datasource.password=${DB_PASSWORD:splitit}

spring.threads.virtual.enabled=true
